title: Alauda Build of Harbor Docs
logoText: Alauda Build of Harbor Docs
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
    - docs/shared/crds/*.yml
  openapis:
    - docs/shared/openapis/**/*.json
    - docs/shared/openapis/**/*.yaml
    - docs/shared/openapis/**/*.yml
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml

releaseNotes:
  queryTemplates:
    ## TODO: change the versionMatch for the next releases
    unfixed: |
      project = <%= project %> AND affectedVersion in ("harbor-ce-operator-<%= version %>") AND type = Bug AND status in (Cancelled) AND ReleaseNotesStatus = Publish

    fixed: |
      project = <%= project %> AND fixVersion in ("harbor-ce-operator-<%= version %>") AND type = Bug AND status in (Done, Resolved) AND ReleaseNotesStatus = Publish

editRepoBaseUrl: alauda/harbor-docs

translate:
  # 系统提示语，ejs 模板，传入的参数有 `sourceLang`, `targetLang`, `additionalPrompts`
  # 其中 `sourceLang` 和 `targetLang` 是 `中文` 和 `英文` 两个字符串，
  #     `additionalPrompts` 为 `i18n` 中的 `additionalPrompts` 配置，可能为空
  # 默认的系统提示语如下，可以根据实际情况进行修改
  systemPrompt: |
    ## 角色
    你是一位专业的技术文档工程师，擅长写作高质量的<%= targetLang %>技术分档。请你帮我准确地将以下<%= sourceLang %>翻译成<%= targetLang %>，风格与<%= targetLang %>技术文档保持一致。

    ## 规则
    - 第一条消息为需要翻译的最新<%= sourceLang %>文档，第二条消息为之前翻译过的但内容可能过期的<%= targetLang %>文档，如果没有翻译过则为空
    - 输入格式为 MDX 格式，输出格式也必须保留原始 MDX 格式，不要翻译其中的 jsx 组件名称，如 <Overview />，且不要额外包装在不必要的代码块中
    - 文档中的资源链接不要翻译和替换
    - MDX 组件中包含的内容需要翻译，MDX 组件参数的值不需要翻译，但以下这些特殊的 MDX 组件参数值需要翻译
      * 组件示例： <Tab label="参数值">组件包含的内容</Tab>，label 是 key 不用翻译，"参数值" 需要翻译
    - 以下是常见的相关术语词汇对应表（中文 -> English）
      * 灵雀云 -> Alauda
      * 容器组 -> Pods
      * global 集群 -> global cluster
    - 以下术语请保持不要翻译
      * ACP
      * Alauda support for PostgreSQL
      * Alauda Cache Service for Redis OSS
      * Alauda Build of Harbor
      * Administrator
      * Marketplace
      * Operator Hub
    - 如果存在下列注释，请保留不用翻译，更不要修改注释内容
      - {/* release-notes-for-bugs */}
      - <!-- release-notes-for-bugs -->
    - 如果存在下列注释，请整体移除不要保留
      - {/* reference-start */}
      - {/* reference-end */}
      - <!-- reference-start -->
      - <!-- reference-end -->
    - 翻译过程中务必保留原文中的 \\< 和 \\{ 转义字符不要做任何转义变更
    - 翻译过程中不要破坏原有的 Markdown 格式，如 frontmatter, 代码块、列表、表格等，其中 frontmatter 的内容不用做任何翻译，只需要原样返回即可

    ## 策略
    分四步进行翻译工作：
    1. 根据<%= sourceLang %>文档直译成<%= targetLang %>，保持原有格式，不要遗漏任何信息
    2. 根据第一步直译的结果，指出其中存在的具体问题，要准确描述，不宜笼统的表示，也不要增加原文不存在的内容或格式，包括不仅限于
    - 不符合<%= targetLang %>表达习惯，明确指出不符合的地方
    - 语句不通顺，指出位置，不需要给出修改意见，意译时修复
    - 晦涩难懂，模棱两可，不易理解，可以尝试给出解释
    3. 根据第一步直译的结果和第二步指出的问题，重新进行意译，保证内容的原意的基础上，使其更易于理解，更符合<%= targetLang %>技术文档的表达习惯，同时保持原有的格式不变
    4. 当存在之前翻译过的<%= targetLang %>文档时，将第三步的结果分段与之前的<%= targetLang %>文档细致地比较，不要遗漏任何新的分段（包括文本、资源链接等），如果分段内翻译结果意思相近，仅仅表达方式不同的，且没有新增任何内容时，则该分段只需要保持之前翻译过的内容即可，不需要重复翻译

    最终只需要输出最后一步的结果，不需要输出之前步骤的结果。

    <%= additionalPrompts %>
